ALTER TABLE SPRING.BOARD
 DROP PRIMARY KEY CASCADE;

DROP TABLE SPRING.BOARD CASCADE CONSTRAINTS;

CREATE TABLE SPRING.BOARD
(
  ID                NUMBER                      NOT NULL,
  SUBJECT           VARCHAR2(1000 BYTE),
  CONTENT           VARCHAR2(4000 BYTE),
  EMAIL             VARCHAR2(100 BYTE),
  CRT_DT            DATE,
  MDFY_DT           DATE,
  FILE_NAME         VARCHAR2(1000 BYTE),
  ORIGIN_FILE_NAME  VARCHAR2(1000 BYTE)
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX SPRING.BOARD_PK ON SPRING.BOARD
(ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SPRING.BOARD ADD (
  CONSTRAINT BOARD_PK
  PRIMARY KEY
  (ID)
  USING INDEX SPRING.BOARD_PK
  ENABLE VALIDATE);
