-- MEMBERS VALUE --
Insert into SPRING.MEMBERS
   (EMAIL, NAME, PASSWORD, POINT)
 Values
   ('ff@gmail.com', 'cossack', '123123', 68);
Insert into SPRING.MEMBERS
   (EMAIL, NAME, PASSWORD, POINT)
 Values
   ('hhh@hhh.com', 'HHH', 'hhh', 10);
Insert into SPRING.MEMBERS
   (EMAIL, NAME, PASSWORD, POINT)
 Values
   ('dkdidl@gmail.com', 'coskk', '456789', 22);
COMMIT;

-- MEMBERS SQL --
ALTER TABLE SPRING.MEMBERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE SPRING.MEMBERS CASCADE CONSTRAINTS;

CREATE TABLE SPRING.MEMBERS
(
  EMAIL     VARCHAR2(100 BYTE)                  NOT NULL,
  NAME      VARCHAR2(100 BYTE)                  NOT NULL,
  PASSWORD  VARCHAR2(100 BYTE)                  NOT NULL,
  POINT     INTEGER                             DEFAULT 0
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX SPRING.MEMBERS_PK ON SPRING.MEMBERS
(EMAIL)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SPRING.MEMBERS ADD (
  CONSTRAINT MEMBERS_PK
  PRIMARY KEY
  (EMAIL)
  USING INDEX SPRING.MEMBERS_PK
  ENABLE VALIDATE);