
﻿ALTER TABLE YOUTUBE.VIDEO
 DROP PRIMARY KEY CASCADE;

DROP TABLE YOUTUBE.VIDEO CASCADE CONSTRAINTS;

CREATE TABLE YOUTUBE.VIDEO
(
  VIDEO_ID      VARCHAR2(20 CHAR)               NOT NULL,
  CHANNEL_ID    VARCHAR2(20 CHAR)               NOT NULL,
  TITLE         VARCHAR2(100 CHAR)              NOT NULL,
  UPLOADER_ID     VARCHAR2(100 CHAR),
  RUNNING_TIME  NUMBER                          DEFAULT 0                     NOT NULL,
  VIEW_COUNT    NUMBER                          NOT NULL,
  UPLOAD_DATE   TIMESTAMP(6)                    NOT NULL,
  POSTER_PATH   VARCHAR2(1000 CHAR)             NOT NULL,
  VIDEO_PATH    VARCHAR2(1000 CHAR)             NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX YOUTUBE.VIDEO_PK ON YOUTUBE.VIDEO
(VIDEO_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE YOUTUBE.VIDEO ADD (
  CONSTRAINT VIDEO_PK
  PRIMARY KEY
  (VIDEO_ID)
  USING INDEX YOUTUBE.VIDEO_PK
  ENABLE VALIDATE);
=======
﻿ALTER TABLE YOUTUBE.VIDEO
 DROP PRIMARY KEY CASCADE;

DROP TABLE YOUTUBE.VIDEO CASCADE CONSTRAINTS;

CREATE TABLE YOUTUBE.VIDEO
(
  VIDEO_ID      VARCHAR2(20 CHAR)               NOT NULL,
  CHANNEL_ID    VARCHAR2(20 CHAR)               NOT NULL,
  TITLE         VARCHAR2(100 CHAR)              NOT NULL,
  UPLOADER_ID     VARCHAR2(100 CHAR),
  RUNNING_TIME  NUMBER                          DEFAULT 0                     NOT NULL,
  VIEW_COUNT    NUMBER                          NOT NULL,
  UPLOAD_DATE   TIMESTAMP(6)                    NOT NULL,
  POSTER_PATH   VARCHAR2(1000 CHAR)             NOT NULL,
  VIDEO_PATH    VARCHAR2(1000 CHAR)             NOT NULL
)
TABLESPACE USERS
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX YOUTUBE.VIDEO_PK ON YOUTUBE.VIDEO
(VIDEO_ID)
LOGGING
TABLESPACE USERS
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE YOUTUBE.VIDEO ADD (
  CONSTRAINT VIDEO_PK
  PRIMARY KEY
  (VIDEO_ID)
  USING INDEX YOUTUBE.VIDEO_PK
  ENABLE VALIDATE);
>>>>>>> e62c116c00582d7c6c3305a3bef2895a0d68c33c
