/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.30
 * Generated at: 2018-09-11 08:56:17 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.view.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class top_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/Source/workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/HuCloud/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1455595374000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"div.login\").hide();\r\n");
      out.write("\t\r\n");
      out.write("\tvar isShow = false;\r\n");
      out.write("\t\r\n");
      out.write("\t$(\"span.login\").click(function() {\r\n");
      out.write("\t\tif(isShow) {\r\n");
      out.write("\t\t\t$(\"div.login\").slideUp(\"fast\");\r\n");
      out.write("\t\t\tisShow = false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\telse {\r\n");
      out.write("\t\t\t$(\"div.login\").slideDown(\"fast\");\r\n");
      out.write("\t\t\t$(\"#id\").focus();\r\n");
      out.write("\t\t\tisShow = true;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".login .loginButton\").click(function() {\r\n");
      out.write("\t\tif( $(\"#id\").val() == \"\" ) {\r\n");
      out.write("\t\t\talert(\"ID를 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"#id\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif( $(\"#password\").val() == \"\" ) {\r\n");
      out.write("\t\t\talert(\"Password를 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"#password\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t// member/login ->memberlogin\r\n");
      out.write("\t\t$.post(\"/HuCloud/memberlogin\", $(\"#loginForm\").serialize(), function(data) {\r\n");
      out.write("\t\t\tif(data == \"OK\") {\r\n");
      out.write("\t\t\t\talert(\"로그인이 완료되었습니다. 페이지를 새로고침합니다.\");\r\n");
      out.write("\t\t\t\tlocation.href=\"/HuCloud/member\";\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if (data = \"BLOCK_ACCOUNT\"){\r\n");
      out.write("\t\t\t\talert(\"비밀번호가 3회 이상 틀려 계정이 잠겼습니다. 1시간 후 다시 시도해 주세요.\")\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\talert(\"로그인이 실패했습니다. 아이디 혹은 비밀번호를 확인해 주세요.\");\r\n");
      out.write("\t\t\t\t$(\"#id\").focus();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".register\").hide();\r\n");
      out.write("\tfullBlock().hide();\r\n");
      out.write("\t$(\".login .registButton\").click(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\"span.login\").click();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar left = $(window).width() / 2;\r\n");
      out.write("\t\tvar top = $(window).height() / 2;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tvar regWidth = 170 / 2;\r\n");
      out.write("\t\tvar regHeight = 170 / 2;\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfullBlock().show();\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".register\").css({\r\n");
      out.write("\t\t\t\"top\" : (top - regHeight) + \"px\",\r\n");
      out.write("\t\t\t\"left\" : (left - regWidth) + \"px\"\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".register\").fadeIn(\"fast\");\r\n");
      out.write("\t\t$(\"#userId\").focus();\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".register .loginButton\").click(function() {\r\n");
      out.write("\t\tfullBlock().hide();\r\n");
      out.write("\t\t$(\".register\").fadeOut(\"fast\");\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".register .registButton\").click(function() {\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif( $(\"#userId\").val() == \"\" ) {\r\n");
      out.write("\t\t\talert(\"ID를 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"#userId\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif( $(\"#userPassword\").val() == \"\" ) {\r\n");
      out.write("\t\t\talert(\"Password를 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"#userPassword\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif( $(\"#userPasswordConfirm\").val() == \"\" ) {\r\n");
      out.write("\t\t\talert(\"Password를 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"#userPasswordConfirm\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tif( $(\"#userName\").val() == \"\" ) {\r\n");
      out.write("\t\t\talert(\"Name을 입력하세요!\");\r\n");
      out.write("\t\t\t$(\"#userName\").focus();\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tif( $(\"#userPassword\").val() != $(\"#userPasswordConfirm\").val() ) {\r\n");
      out.write("\t\t\talert(\"Password 가 일치하지 않습니다!\");\r\n");
      out.write("\t\t\treturn;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$.post(\"/HuCloud/member/registry\", $(\"#registerForm\").serialize(), function(data) {\r\n");
      out.write("\t\t\tif(data == \"OK\") {\r\n");
      out.write("\t\t\t\talert(\"회원가입이 완료되었습니다!\");\r\n");
      out.write("\t\t\t\t$(\"span.login\").click();\r\n");
      out.write("\t\t\t\t$(\"#id\").val($(\"#userId\").val());\r\n");
      out.write("\t\t\t\t$(\"#password\").focus();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse if ( data = PASS_POLICY_VIOLATION ){\r\n");
      out.write("\t\t\t\talert(\"패스워드가 잘못되었습니다. (숫자, 영문자(대소문자포함), 특수문자 포함하여 최소 8글자 이상)\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\telse {\r\n");
      out.write("\t\t\t\talert($(\"#userId\").val()+ \"은(는) 이미 존재하는 아이디 입니다.\");\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$(\".register .loginButton\").click();\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("function fullBlock() {\r\n");
      out.write("\tvar width = $(window).width();\r\n");
      out.write("\tvar height = $(window).height();\r\n");
      out.write("\t\r\n");
      out.write("\t$(\".blockDiv\").css({\r\n");
      out.write("\t\t\"width\" : width + \"px\",\r\n");
      out.write("\t\t\"height\": height + \"px\",\r\n");
      out.write("\t\t\"opacity\" : \"0.5\"\r\n");
      out.write("\t});\r\n");
      out.write("\t\r\n");
      out.write("\treturn $(\".blockDiv\");\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("<div class=\"blockDiv\"></div>\r\n");
      out.write("<div class=\"login\">\r\n");
      out.write("\t<div class=\"wrapper\">\r\n");
      out.write("\t\t<form id=\"loginForm\" name=\"loginForm\">\r\n");
      out.write("\t\t\t<input type=\"text\" name=\"id\" id=\"id\" class=\"tip\" placeholder=\"ID\" />\r\n");
      out.write("\t\t\t<input type=\"password\" name=\"password\" id=\"password\" placeholder=\"Password\"/>\r\n");
      out.write("\t\t\t<span class=\"button loginButton\">Login</span>\r\n");
      out.write("\t\t\t<span class=\"button registButton\">Sign Up</span>\r\n");
      out.write("\t\t</form>\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"register\">\r\n");
      out.write("\t<form id=\"registerForm\" name=\"registerForm\">\r\n");
      out.write("\t\t<input type=\"text\" name=\"userId\" id=\"userId\" placeholder=\"ID\"/><br/>\r\n");
      out.write("\t\t<div class=\"spacer\"></div>\r\n");
      out.write("\t\t<input type=\"password\" name=\"userPassword\" id=\"userPassword\" placeholder=\"Password\"/><br/>\r\n");
      out.write("\t\t<div class=\"spacer\"></div>\r\n");
      out.write("\t\t<input type=\"password\" name=\"userPasswordConfirm\" id=\"userPasswordConfirm\" placeholder=\"Password Confirm\"/><br/>\r\n");
      out.write("\t\t<div class=\"spacer\"></div>\r\n");
      out.write("\t\t<input type=\"text\" name=\"userName\" id=\"userName\" placeholder=\"name\"/><br/>\r\n");
      out.write("\t\t<div class=\"spacer\"></div>\r\n");
      out.write("\t\t<span class=\"button registButton\">Sign Up</span>\r\n");
      out.write("\t\t<span class=\"button loginButton\">Cancel</span>\r\n");
      out.write("\t</form>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"wrapper\">\r\n");
      out.write("\t<div style=\"vertical-align: top;\">\r\n");
      out.write("\t\t<img src=\"/HuCloud/resources/img/hucloud-logo_60.png\" style=\"float:left;\" />\r\n");
      out.write("\t\t<img src=\"/HuCloud/resources/img/security.PNG\" width=\"130\" style=\"float:left;padding-top:5px;\"/>\r\n");
      out.write("\t\t<span class=\"login link\" style=\"float:right;padding-top: 5px; padding-right: 5px;\">Login</span>\r\n");
      out.write("\t\t<div style=\"clear:both;\"></div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<div class=\"spacer\"></div>\r\n");
      out.write("\t");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"tooltip\"></div>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005fimport_005f0.setParent(null);
    // /WEB-INF/view/common/top.jsp(177,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
    _jspx_th_c_005fimport_005f0.setUrl("/common/menu");
    int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
      if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_c_005fimport_005f0.doFinally();
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
    }
    return false;
  }
}
