ALTER TABLE SYSTEM.BOARD
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYSTEM.BOARD CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.BOARD
(
  ID                NUMBER                      NOT NULL,
  SUBJECT           VARCHAR2(1000 BYTE),
  CONTENT           VARCHAR2(4000 BYTE),
  USER_ID           VARCHAR2(100 BYTE),
  CRT_DT            DATE,
  MDFY_DT           DATE,
  HIT               NUMBER,
  RECOMMEND         NUMBER,
  FILE_NAME         VARCHAR2(1000 BYTE),
  ORIGIN_FILE_NAME  CHAR(1000 BYTE)
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX SYSTEM.BOARD_PK ON SYSTEM.BOARD
(ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SYSTEM.BOARD ADD (
  CONSTRAINT BOARD_PK
  PRIMARY KEY
  (ID)
  USING INDEX SYSTEM.BOARD_PK
  ENABLE VALIDATE);