ALTER TABLE SYSTEM.REPLY
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYSTEM.REPLY CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.REPLY
(
  ID         NUMBER                             NOT NULL,
  BOARD_ID   NUMBER                             NOT NULL,
  CONTENT    VARCHAR2(4000 BYTE),
  USER_ID    VARCHAR2(100 BYTE),
  CRT_DT     DATE,
  MDFY_DT    DATE,
  RECOMMEND  NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX SYSTEM.REPLY_PK ON SYSTEM.REPLY
(ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SYSTEM.REPLY ADD (
  CONSTRAINT REPLY_PK
  PRIMARY KEY
  (ID)
  USING INDEX SYSTEM.REPLY_PK
  ENABLE VALIDATE);