ALTER TABLE SYSTEM.USERS
 DROP PRIMARY KEY CASCADE;

DROP TABLE SYSTEM.USERS CASCADE CONSTRAINTS;

CREATE TABLE SYSTEM.USERS
(
  USER_ID           VARCHAR2(100 BYTE)          NOT NULL,
  USER_NAME         VARCHAR2(100 BYTE),
  USER_PASSWORD     VARCHAR2(500 BYTE),
  IS_ADMIN_YN       VARCHAR2(3 BYTE),
  CRT_DT            DATE,
  MDFY_DT           DATE,
  SALT              VARCHAR2(100 BYTE),
  LAST_LOGIN        TIMESTAMP(6),
  LOGIN_FAIL_COUNT  NUMBER
)
TABLESPACE SYSTEM
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX SYSTEM.USERS_PK ON SYSTEM.USERS
(USER_ID)
LOGGING
TABLESPACE SYSTEM
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE SYSTEM.USERS ADD (
  CONSTRAINT USERS_PK
  PRIMARY KEY
  (USER_ID)
  USING INDEX SYSTEM.USERS_PK
  ENABLE VALIDATE);